version: '2'

networks:
    backend:
        driver: 'bridge'

services:

   harlanzw:
    container_name: harlanzw
    # Uncomment the below if you need to rebuild the container
    build: ./env/docker/
    restart: always
#    image: 4mation/wordpress:v5.3
    domainname: local.harlanzw.com
    environment:
      - DB_NAME=hzw
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_HOST=hzw_db
      - VIRTUAL_HOST=local.harlanzw.com
      - HTTPS_METHOD=noredirect
    ports:
        - 80:80
    extra_hosts:
      - "local.harlanzw.com:127.0.0.1"
#    This IP is not always correct, it's just what was the host-machine IP at the time
      - "host-machine:172.17.0.1"
    volumes:
         - .:/home/wp/code
         - /home/harlan/.ssh:/home/wp/.ssh
    networks:
        - backend

   hzw_db:
    container_name: hzw_db
    image: mariadb
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=hzw
    ports:
      - "3311:3306"
    volumes:
      - ./env/database:/var/lib/mysql
    networks:
        - backend
