<?php
return [
    [
        'key' => 'field_5a41bb9c19d12',
        'label' => 'Background Image',
        'name' => 'background_image',
        'type' => 'image',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => [
            'width' => '',
            'class' => '',
            'id' => '',
        ],
        'return_format' => 'id',
        'preview_size' => 'medium',
        'library' => 'all',
        'min_width' => 1440,
        'min_height' => 460,
        'min_size' => '',
        'max_width' => '',
        'max_height' => '',
        'max_size' => '',
        'mime_types' => '',
    ],
    [
        'key' => 'field_58e1bf94fb251',
        'label' => 'Title',
        'name' => 'title',
        'type' => 'text',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => [
            'width' => '',
            'class' => '',
            'id' => '',
        ],
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'maxlength' => '',
    ],
    [
        'key' => 'field_58e1bfa1fb252',
        'label' => 'Sub Title',
        'name' => 'sub_title',
        'type' => 'text',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => [
            'width' => '',
            'class' => '',
            'id' => '',
        ],
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'maxlength' => '',
    ],
    [
        'key' => 'field_58e1bfb0fb253',
        'label' => 'Buttons',
        'name' => 'buttons',
        'type' => 'repeater',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => [
            'width' => '',
            'class' => '',
            'id' => '',
        ],
        'collapsed' => 'field_58e1bfc2fb255',
        'min' => 0,
        'max' => 2,
        'layout' => 'table',
        'button_label' => 'Add Button',
        'sub_fields' => [
            [
                'key' => 'field_590197947712a',
                'label' => 'Link Relation',
                'name' => 'link_relation',
                'type' => 'select',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
                'choices' => [
                    'regular' => 'Regular',
                    'wysiwyg' => 'WYSIWYG',
                ],
                'default_value' => [
                    0 => 'regular',
                ],
                'allow_null' => 0,
                'multiple' => 0,
                'ui' => 1,
                'ajax' => 0,
                'return_format' => 'value',
                'placeholder' => '',
            ],
            [
                'key' => 'field_58e1bfbbfb254',
                'label' => 'Link URL',
                'name' => 'link',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => [
                    [
                        [
                            'field' => 'field_590197947712a',
                            'operator' => '==',
                            'value' => 'regular',
                        ],
                    ],
                ],
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ],
            [
                'key' => 'field_58e1bfc2fb255',
                'label' => 'Button Text',
                'name' => 'button_text',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '21',
            ],
            [
                'key' => 'field_58e1bfdffb256',
                'label' => 'Link Type',
                'name' => 'link_type',
                'type' => 'select',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => [
                    [
                        [
                            'field' => 'field_590197947712a',
                            'operator' => '==',
                            'value' => 'regular',
                        ],
                    ],
                ],
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
                'choices' => [
                    'same_window' => 'Same Window',
                    'new_window' => 'New Window',
                ],
                'default_value' => [
                    0 => 'same_window',
                ],
                'allow_null' => 0,
                'multiple' => 0,
                'ui' => 1,
                'ajax' => 0,
                'return_format' => 'value',
                'placeholder' => '',
            ],
        ],
    ],
];
