<?php
return [
    [
        'key' => 'field_59805c5402e1d',
        'label' => 'Image',
        'name' => 'image',
        'type' => 'image',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => [
            'width' => '',
            'class' => '',
            'id' => '',
        ],
        'return_format' => 'id',
        'preview_size' => 'medium',
        'library' => 'all',
        'min_width' => 1440,
        'min_height' => 460,
        'min_size' => '',
        'max_width' => '',
        'max_height' => '',
        'max_size' => '',
        'mime_types' => '',
    ],
    [
        'key' => 'field_59805c4d49636',
        'label' => 'Height',
        'name' => 'height',
        'type' => 'number',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => [
            'width' => '',
            'class' => '',
            'id' => '',
        ],
        'default_value' => '600',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'maxlength' => '',
    ],
    [
        'key' => 'field_59805f041109c',
        'label' => 'Center',
        'name' => 'center',
        'type' => 'number',
        'instructions' => 'This is the center for where the parallax effect will work. Between 0 and 1.',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => [
            'width' => '',
            'class' => '',
            'id' => '',
        ],
        'default_value' => '0.5',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'maxlength' => '',
    ],
    [
        'key' => 'field_59805f19041de',
        'label' => 'Intensity',
        'name' => 'intensity',
        'type' => 'number',
        'instructions' => 'This is the intensity of the scroll on the parallax effect. Between 0 and 100',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => [
            'width' => '',
            'class' => '',
            'id' => '',
        ],
        'default_value' => '30',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'maxlength' => '',
    ],
];
